#version: '3'
#services:
#  spring-app:
#    build: .
#    container_name: spring-boot-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sitedb
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#
#  mysql:
#    image: mysql:8
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: sitedb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - "9092:9092"
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
